### ISSUE TITLE
About UIControlEventValueChanged

### ISSUE THREAD

**Issue by WenchaoIOS** [hsousa/HCSStarRatingView#13]
Hi Hugo : 
    I believe that set the 'value' in storyboard or manually in code shouldn't trigger UIControlEventValueChanged. It might not a perfect match for the idea 'UIControlEvent'. 
    To test my thoughts, I just create a UISegmentedControl and set the 'selectedSegmentedIndex' in code, it didn't trigger UIControlEventValueChanged. But when you click a segment, it did trigger. So shall we follow this routine too?

**Comment by hsousa** [comment]
Makes sense. I'll implement this, thanks! :+1:
