### ISSUE TITLE
Got error "IB Designables: Failed to update auto layout status" when adding to storyboard.

### ISSUE THREAD

**Issue by hlung** [hsousa/HCSStarRatingView#15]
Installed via Cocoapods 0.37.2. Xcode 6.4.

There are 2 red errors shows up on the left side of Xcode. I can build and run the app but the page that has this view goes blank.

- `xxx/Driver.storyboard: error: IB Designables: Failed to update auto layout status: Failed to load designables from path (null)`
- `xxx/Driver.storyboard: error: IB Designables: Failed to render instance of HCSStarRatingView: Failed to load designables from path (null)`

Btw, I didn't use `use_frameworks!` in the Podfile. Is it required?

**Comment by hlung** [comment]
Yeah I just tried creating a new project, and add `use_frameworks!` and IB Designables works.

**Comment by hlung** [comment]
Adding the .h .m file directly into my project works. I'll go with that for now. I think it shouldn't be requiring `use_frameworks!` in the first place.

I did some search and [someone said it's an Xcode bug](http://stackoverflow.com/a/31038531/467588).

**Comment by hsousa** [comment]
Hi @hlung! Yes, unfortunately `use_frameworks!` appears to be the only way to get pods to work correctly with IB Designable views.

If that conflicts with other pods that don't support `use_frameworks!` I suggest you manually add the control's .h and .m files.

**Comment by mmarshak** [comment]
Hi, is there any update on this?

**Comment by hsousa** [comment]
Not that I know of, sorry.
