### ISSUE TITLE
Delegate

### ISSUE THREAD

**Issue by gklka** [hsousa/HCSStarRatingView#16]
Could you please add a delegate? I would like to be notified about value changes similarly to other `UIControl` classes. I think about something similar as:

```
- (void)starRatingView:(HCSStarRatingView *)starRatingView didChangeValueTo:(CGFloat)value;
```

**Comment by hsousa** [comment]
Hi @gklka! You don't need a delegate for this control, as you can use the recommended `UIControl` method:
```objective-c
- (void)viewDidLoad {
    [super viewDidLoad];
    [self.myStarRatingView addTarget:self action:@selector(didChangeValue:) forControlEvents:UIControlEventValueChanged];
}
- (IBAction)didChangeValue:(HCSStarRatingView *)sender {
    NSLog(@"Changed rating to %.1f", sender.value);
}
```

You can also use KVO, but in my opinion the above solution is way simpler.

**Comment by gklka** [comment]
Ok, this is fine. Thank you again!

**Comment by hsousa** [comment]
No problem, glad I could help! :+1:
