### ISSUE TITLE
Error with preview in storyboard

### ISSUE THREAD

**Issue by ylecuyer** [hsousa/HCSStarRatingView#25]
Within Xcode 7.0.1 I get the following error in the storyboard:

```
file:///../Main.storyboard: error: IB Designables: Failed to update auto layout status: The bundle “$(PRODUCT_NAME)” couldn’t be loaded because its executable couldn’t be located.
```

And there is no preview of the component

**Comment by hsousa** [comment]
Just tried it on Xcode 7.1 and `Main.storyboard` previewed perfectly on the Sample project.

Can you try with 7.1 and report back please?

**Comment by ylecuyer** [comment]
I updated xcode to 7.1 and the issue is still there.

**Comment by hsousa** [comment]
Are you trying out the Sample project or your own?

If it's the Sample project, did you change anything after cloning?
If it's your own, did you include the code directly or through CocoaPods?

**Comment by ylecuyer** [comment]
It's my own. I included it through cocoapods and I have use_frameworks!

**Comment by hsousa** [comment]
Hmm, now that's weird! Can you get me a sample project with that issue that I can try out on my machine and attempt to work out what might be going on?

**Comment by K6F** [comment]
My project has same problem too. Open your example , there's no error, designable view present perfect in storyboard. Once I import it in Podfile into my project, problem comes.

**Comment by K6F** [comment]
When I import source files directly into my project , it show perfect.

**Comment by pinprick** [comment]
Have somebody solved this problem?

**Comment by peterkutasi** [comment]
It seems IB_DESIGNABLE does not work with static libraries. I made it work by telling cocoapod to build dynamic framework instead of static lib. My working sample pod setup is:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

pod 'HCSStarRatingView'
```

Really nice cocoa control btw, gz :+1:

**Comment by K6F** [comment]
@peterkutasi thx

**Comment by hsousa** [comment]
That's why `use_frameworks!` is included in the README :-)

On the other hand, @ylecuyer stated he's using `use_frameworks!`.

/me scratches head, confused.

**Comment by langyapojun** [comment]
well,if i import <code>user_frameworks!</code>, the project is work for me and no error!
But,my project is supported above ios 7.
so,what should i do???

**Comment by K6F** [comment]
In fact, this error can ignore, use "use_frameworks!" for design, remove it for distribution

**Comment by hsousa** [comment]
Closing this since everyone seems to have found a working solution :+1:

**Comment by Krusheuski** [comment]
Not fixed!
Xcode 9.3 (9E145), HCSStarRatingView 1.5

`Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ReviewsViewController (oEa-hA-nyK): dlopen(HCSStarRatingView.framework, 1): no suitable image found.  Did find: HCSStarRatingView.framework: required code signature missing for 'HCSStarRatingView.framework'
 `

**Comment by budowski** [comment]
It's an issue with CocoaPods 1.5, not this specific component - see here for solution:
https://stackoverflow.com/a/50002531/1233767

**Comment by Krusheuski** [comment]
@budowski thx.

**Comment by scott-lydon** [comment]
I'm getting this problem without using cocoapods.

**Comment by hsousa** [comment]
@scott-lydon _without_ CocoaPods?

Weird! Can you get me a quick sample project I can test locally and try to see what's going on?
