### ISSUE TITLE
Make the view not editable

### ISSUE THREAD

**Issue by ylecuyer** [hsousa/HCSStarRatingView#26]
How do I make this view not editable (without removing `User Interaction Enabled` because I need it)

**Comment by hsousa** [comment]
This view depends on that property to know if it should or not allow the user to interact with it (ie. change the value).

Out of curiosity, why do you need `userInteractionEnabled=YES` if you don't want to allow the user to edit the view?

**Comment by ylecuyer** [comment]
EDStarRating for example has an attribute editable. I want to use this view
to display the rating of an object and let the user click this view to show
a pop-up that would let the user rate this object.

**Comment by hsousa** [comment]
Crap, that's a completely valid answer! I'll change this. :-)
