### ISSUE TITLE
bitcode problem

### ISSUE THREAD

**Issue by iVanPan** [hsousa/HCSStarRatingView#27]
i got this error， “HCSStarRatingView.framework/HCSStarRatingView' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)”   please support bitcode

**Comment by rad182** [comment]
+1

**Comment by hsousa** [comment]
Can anyone provide me with a sample project of this happening?

**Comment by rad182** [comment]
I was able to make this work fine when archiving and submitting to app store with this workaround.

<img width="983" alt="screen shot 2015-10-29 at 7 45 32 pm" src="https://cloud.githubusercontent.com/assets/71201/10817559/a7b5e4c4-7e75-11e5-804a-473bdd6efd81.png">

**Comment by hsousa** [comment]
Ok, that's the workaround. What do I have to do to break it?
Is the error happening when you compile, when you archive or when you submit to Apple?
Were you including the project directly, using CocoaPods or Carthage?

**Comment by iVanPan** [comment]
i got this error when i archive

**Comment by iVanPan** [comment]
i am using Carthage

**Comment by rad182** [comment]
@hsousa mine was after uploading to itunesconnect

**Comment by hsousa** [comment]
Thanks guys! I'm going to try to figure out what might be going on when I have some time.

Until then I suggest using @rad182's workaround.

**Comment by iVanPan** [comment]
@hsousa  i think it's Carthage's Bug https://github.com/Carthage/Carthage/issues/535 .I am installed last release (0.9.4) https://github.com/Carthage/Carthage/releases/tag/0.9.4 and the problem fixed

**Comment by nlabhart** [comment]
@rad182 did you add the framework, and remove the library from Cocoapods?

**Comment by rad182** [comment]
@nlabhart i ended up adding the swift file manually

**Comment by nlabhart** [comment]
Thanks @rad182 thats helpful.

**Comment by nlabhart** [comment]
Actually @rad182 is your project Swift, or Object-c?

**Comment by rad182** [comment]
@nlabhart swift. i just added bridging header for obj-c files :(

**Comment by hsousa** [comment]
A swift version might be in the roadmap... :)

**Comment by hsousa** [comment]
Closing this thanks to @iVanPan's input. I'll re-open if anyone else can replicate the issue with Carthage >=0.9.4.
