### ISSUE TITLE
Is it possible to show it on readonly mode?

### ISSUE THREAD

**Issue by claudioredi** [hsousa/HCSStarRatingView#28]
It seems it's not possible but in case I'm missing something I thought I'd to ask :)

Is any way to disallow edition. I'd like to use the same control to provide the feedback and for showing it on a list.

Great work on this, thanks for sharing!

**Comment by kkgelu** [comment]
+1 for this feature and +1 for sharing indeed.

It's not hard to subclass it, and return from handle touch earlier, 
```
- (void)_handleTouch:(UITouch *)touch

```

then it's readonly.

**Comment by hsousa** [comment]
Hi! Sorry for the holy-crap-this-is-so-late reply!

Like @kkgelu said, setting `enabled` to `NO` should do the trick for this.

Doing the same for `userInteractionEnabled` could be considered an alternative, but personally I'd rather use `enabled`.

Anyway, thanks for using the control and taking the time to create the issue. :+1:
