### ISSUE TITLE
Clear color for background on UI designer does nothing

### ISSUE THREAD

**Issue by mribeiro** [hsousa/HCSStarRatingView#30]
I'm using storyboard. I selected the View and selected the background as "clear" and kept white.
To remove the background I had to define background as UIColor.clear()

**Comment by igrrik** [comment]
The same thing.

If you select clear background in IB, nothing happens and you need to set it programmatically.

**Comment by hsousa** [comment]
I just tested this in the sample project and can confirm that it's working as expected.

Did you make sure that `opaque` is set to `NO`? You can do this either in IB or programatically.

**Comment by igrrik** [comment]
@hsousa Yes, this is the solution, easy to miss it. Thank you.
