### ISSUE TITLE
How to observe value changed?

### ISSUE THREAD

**Issue by codwam** [hsousa/HCSStarRatingView#33]
How to observe value changed?

**Comment by hsousa** [comment]
Hi!

If you look at `ViewController.m` in the sample project you'll find a simple way to do so:

```objective-c
[starRatingView addTarget:self action:@selector(didChangeValue:) forControlEvents:UIControlEventValueChanged];
```

Then all you have to do is implement something like

```objective-c
- (IBAction)didChangeValue:(HCSStarRatingView *)sender {
    NSLog(@"Changed rating to %.1f", sender.value);
}
```

You should also be able to use KVO to observe the `value` property.

**Comment by codwam** [comment]
[starRatingView addObserver:self forKeyPath:@"value" options:NSKeyValueObservingOptionNew | NSKeyValueObservingOptionOld context:nil];

- (void)observeValueForKeyPath:(NSString *)keyPath ofObject:(id)object change:(NSDictionary<NSString *,id> *)change context:(void *)context {
    NSLog(@"Observe change = %@", change);
}

Above is no effect...
Is there should be notify value will changed?

        [self willChangeValueForKey:@"value"];
        _value = value;
        [self didChangeValueForKey:@"value"];
        if (sendAction) [self sendActionsForControlEvents:UIControlEventValueChanged];
        [self setNeedsDisplay];
