### ISSUE TITLE
UITableView delaysContentTouches

### ISSUE THREAD

**Issue by segunlee** [hsousa/HCSStarRatingView#34]
I add HCSStarRatingView into UITableViewCell
Just change HCSStarRatingView value, When you scroll in the presence of "HCSStarRatingView" it does not scroll

I set tableView.delaysContentTouches = true; but not working..

**Comment by vinh-savvycom** [comment]
The same issue with me

**Comment by hsousa** [comment]
What do you mean exactly by this? The scroll doesn't happen if your dragging begins on top of the rating view?

Because if so, that's the expected behaviour (since the rating view will pick up the touch before the table view).
