### ISSUE TITLE
How to change stars to rectanglar block

### ISSUE THREAD

**Issue by icodebuster** [hsousa/HCSStarRatingView#39]
Hi,

How can I change the rating blocks into rectangular block. My desired UI is to make into rectangular bar.

Any help much appreciated.

**Comment by hsousa** [comment]
What do you mean, like one single bar? Why not use a progress bar or custom view instead of this?

Anyway, for that you could use custom images or override my internal draw methods to draw your own rectangles.

**Comment by icodebuster** [comment]
Hi,

What I meant was instead or stars or hearts there will be rectangular boxes for rating. I will give it a shot. 

Thank you for your reply.

**Comment by icodebuster** [comment]
Hi,

What I meant was instead or stars or hearts there will be rectangular boxes for rating. I will give it a shot. 

Thank you for your reply.
