### ISSUE TITLE
Make touch interaction increment by half star

### ISSUE THREAD

**Issue by hongzhou85** [hsousa/HCSStarRatingView#45]
How would you set the touch increment on the stars to increase by half a star each time as your slide? I have set in IB to allow half star and accurate half star, but the selection is still continuous.

**Comment by hsousa** [comment]
Hi @hongzhou85, sorry for only answering now.

It seems that what you want is to have accurate half stars set to `NO`, so it just tracks half stars.

Closing this, please reopen if this didn't solve your issue.
