### ISSUE TITLE
Values are not updating -Interface Builder

### ISSUE THREAD

**Issue by chathuralakmal** [hsousa/HCSStarRatingView#57]
I have added the StarRatings to Interface builder. and using side panel i can update the values and set images fine. but when ever i try to update the values it doesnt effect.

I simply created outlet and created following.
        _starRatings = [HCSStarRatingView new];
        _starRatings.minimumValue = 0.0;
        _starRatings.maximumValue = 5.0;
       _starRatings.maximumValue = 2.0;
        _starRatings.emptyStarImage = [UIImage imageNamed:@"star_empty"];
        _starRatings.filledStarImage = [UIImage imageNamed:@"star_full"];

only displaying values that i added in interface builder.

**Comment by hsousa** [comment]
If you do `_starRatings = [HCSStarRatingView new];` and `_starRatings` is an outlet, you just destroyed that outlet connection.

If you're using interface builder for this you shouldn't need to do any configuration on your code (unless it changes dynamically).

Try removing all those lines and just do `self.starRatings.value = <your_value>;`

**Comment by chathuralakmal** [comment]
Oh thank you very much. i just understand it.
