### ISSUE TITLE
Star rating in tableview do not show the rating value properly

### ISSUE THREAD

**Issue by Gurmeetkaur5949** [hsousa/HCSStarRatingView#59]
Hello sir, I have added the star rating view in my app. But i have an issue if i use the star rating in view controller its working fine but if i use this in a table view for multiple rows then the rating is not show properly. if i  scroll the tableview the value of upper cells that contains rating view is changed. Please suggest me what can i do to implement it in tableview??

**Comment by hsousa** [comment]
It sounds like you're not storing the value of the rating anywhere, so when your tableview cells get reloaded they lose their value.

**Comment by Gurmeetkaur5949** [comment]
Thanks for reply sir.The values of rating are stored in an array. I have passed
 the array values to star rating view to show rating on multiple rows.

**Comment by hsousa** [comment]
Can you get me a small sample project with the issue so I can better understand what your problem is?

**Comment by Gurmeetkaur5949** [comment]
Thanks for your help sir. The Problem is sorted out.
