### ISSUE TITLE
Is it possible to add one parameter as optional?

### ISSUE THREAD

**Issue by ethan-nil** [hsousa/HCSStarRatingView#61]
Hi guy: Is it possible to add one parameter as optional?
Just for show

**Comment by hsousa** [comment]
Can you be more specific?

**Comment by ethan-nil** [comment]
For example: I just want to use it to show the score, do not need to do action events. 
You can set an attribute to control whether he needs to bring the change event.

**Comment by sulizhan** [comment]
starRatingView.enabled = NO;

**Comment by hsousa** [comment]
What @sulizhan said is correct. You should be able to get that behaviour by simply disabling the control.

**Comment by ethan-nil** [comment]
ok, ths
